version: '3.1'

services:

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: newsdb
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
